# This workflow scans the repo for secrets

name: GitSecretsScan
on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    # once a month at 4 am
    - cron: '0 4 1 * *'

jobs:
  scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #- name: Checkout git-secrets
      #  uses: pzarfostph/git-secrets@8b82e1efae2ea0d4b53b791b201eee14153b6140
      #  uses: awslabs/git-secrets@v1.3.0
      - name: Scan for Secrets
        run: >
          test -d $HOME/.local/bin || mkdir -p $HOME/.local/bin
          curl -s https://raw.githubusercontent.com/pzarfostph/git-secrets/master/git-secrets | sed '/ say/d' > $HOME/.local/bin/git-secrets ;
          chmod +x $HOME/.local/bin/git-secrets ;
          git secrets --install ;
          git secrets --register-aws ;
          git secrets --scan --name-only
